### ISSUE TITLE
add annotations support to the service

### ISSUE THREAD

**Issue by rvoitenko** [observIQ/bindplane-op-helm#83]
**Is your feature request related to a problem? Please describe.**
Service template doesn’t include annotations. And it's causing problems with Ingress on GKE for clusters where NEGs are not the default(https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#container-native_load_balancing). So you can't create Ingress pointed to Service with ClusterIP in this case.
To fix this I manually added the following annotation to the service:
`cloud.google.com/neg: '{"ingress": true}'`

**Describe the solution you'd like**
Add annotations to the service.

**Comment by jsirianni** [comment]
Hi @rvoitenko, sorry for the delayed response. You can configure service annotations with chart version 1.5.0. https://github.com/observIQ/bindplane-op-helm/releases/tag/bindplane-1.5.0.

https://github.com/observIQ/bindplane-op-helm/blob/main/charts/bindplane/values.yaml#L336-L338
